"""Reference impedances for checking the browser's NEC run.

The page will build its own decks and solve them with nec2c-wasm.  Two
things can go wrong there and look like physics: the geometry can be
ported wrong, and the deck can ask for a different ground than this
model was fitted against.  Both are the same class of mistake as
`buildDeck`'s perfect-ground default, and neither is visible in the
answer.

So the geometry is pinned here.  This writes reference_cases.json: a
set of installations with the feedpoint impedance PyNEC computes for
them, which the browser must reproduce before its output is worth
showing anyone.

PyNEC wraps nec2++ and nec2c-wasm carries Kyriazis's nec2c, so these are
two independent translations of NEC-2 rather than the same code twice.
Close agreement is meaningful; exact agreement is not expected, and
TOLERANCE says how much of a gap should still count as a pass.

**nec2c cannot pass this fixture, and that is not a porting error.**
These cases put the return path 5 cm off the soil, where NEC-2's own
Sommerfeld evaluation misses the conductivity limit by about 30 percent
-- as does the original FORTRAN, so no nec2c fix will close it.  Only
nec2++ reaches the limit; see nec2c_ground_bug.py.  The fixture stays
useful for the mistakes it was built to catch, which are geometry and
ground constants, but a run against nec2c-wasm will fail it wholesale
and the failure says nothing about the port.  Read TOLERANCE as applying
to a nec2++ build.
"""

import json
from pathlib import Path

from nec_model import GROUNDS, RETURN_HEIGHT_M, WIRE_RADIUS_M, end_fed_zin

FT = 0.3048

#: Fractional agreement required of |Z|.  Two NEC-2 translations solving
#: the same deck should land far inside this; a geometry ported wrong
#: will not.
TOLERANCE = 0.02

#: Band centres the page checks, hertz.  One run per band, since nec2c
#: emits a full result block per frequency and the parser takes one.
BAND_CENTRES_HZ = {
    "80m": 3.75e6,
    "40m": 7.15e6,
    "20m": 14.175e6,
    "15m": 21.225e6,
    "10m": 28.85e6,
}

#: Installations to pin.  The page's defaults, then one either side of
#: them, then the corner the model warns about, so a port that is right
#: in the middle and wrong at the edges still fails.
CASES = (
    ("defaults", 71.0, 30.0, 25.0, "average"),
    ("low wire", 71.0, 12.0, 25.0, "average"),
    ("high wire", 84.0, 60.0, 25.0, "average"),
    ("long return", 84.0, 30.0, 100.0, "average"),
    ("poor ground", 107.0, 30.0, 25.0, "poor"),
    ("good ground", 107.0, 30.0, 25.0, "good"),
)

OUTPUT = Path(__file__).resolve().parent / "reference_cases.json"


def build():
    cases = []
    for name, length_ft, height_ft, return_ft, soil in CASES:
        eps, sigma = GROUNDS[soil]
        bands = {}
        for band, freq_hz in BAND_CENTRES_HZ.items():
            z = end_fed_zin(
                length_ft * FT, freq_hz, height_ft * FT, return_ft * FT, ground=soil
            )
            bands[band] = {
                "freq_hz": freq_hz,
                "r": round(z.real, 3),
                "x": round(z.imag, 3),
            }
        cases.append(
            {
                "name": name,
                "length_ft": length_ft,
                "height_ft": height_ft,
                "return_ft": return_ft,
                "soil": soil,
                "ground": {"eps": eps, "sigma_s_per_m": sigma},
                "bands": bands,
            }
        )
    return {
        "note": (
            "Generated by nec/random_wire/reference_cases.py from PyNEC.  "
            "The browser's nec2c-wasm run must reproduce these to within "
            "tolerance before its output is shown."
        ),
        "geometry": (
            "Antenna wire horizontal at height_ft, fed at the end nearest "
            "the drop; vertical drop from the feedpoint to return_height_m; "
            "return run horizontal at that height, same direction as the "
            "antenna.  One radius throughout."
        ),
        "wire_radius_m": WIRE_RADIUS_M,
        "return_height_m": RETURN_HEIGHT_M,
        "segments_per_wavelength": 20,
        "ground_card": "GN 2 (Sommerfeld), not GN 1",
        "tolerance": TOLERANCE,
        "cases": cases,
    }


if __name__ == "__main__":
    data = build()
    OUTPUT.write_text(json.dumps(data, indent=2) + "\n")
    print(f"wrote {OUTPUT}")
    for case in data["cases"]:
        z = case["bands"]["20m"]
        print(
            f"  {case['name']:14} {case['length_ft']:6.1f} ft  "
            f"20m: {z['r']:9.1f} {z['x']:+9.1f}j"
        )
